steps:
  - name: gcr.io/k8s-skaffold/pack
    args:
      - '-c'
      - |
        pack build \
          "$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA" \
          --builder=gcr.io/buildpacks/builder:latest \
          --network=cloudbuild \
          --publish \
          --path=. \
          --env="POSTGRES_URL=$$POSTGRES_URL" \
          --env="STORAGE_POSTGRES_URL=$$STORAGE_POSTGRES_URL"
    id: Buildpack
    entrypoint: sh
    secretEnv:
      - POSTGRES_URL
      - STORAGE_POSTGRES_URL
  - name: gcr.io/cloud-builders/docker
    args:
      - pull
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Pull
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _AR_HOSTNAME: europe-west1-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy
  _AR_PROJECT_ID: finance-dashboard-27082026
  _PLATFORM: managed
  _SERVICE_NAME: finance-dashboard
  _DEPLOY_REGION: europe-west1
  _TRIGGER_ID: b4f3236c-be9d-4667-a8f1-64d29b852208
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - finance-dashboard
availableSecrets:
  secretManager:
    - versionName: projects/finance-dashboard-27082026/secrets/POSTGRES_URL/versions/latest
      env: POSTGRES_URL
    - versionName: >-
        projects/finance-dashboard-27082026/secrets/STORAGE_POSTGRES_URL/versions/latest
      env: STORAGE_POSTGRES_URL
